#!/usr/bin/env python3
"""Lane #203 — executable reference semantics of the minimal OCM substrate.

Operator directive (#194, comment 5539487737, 2026-09-04): the object of study is
the *substrate + constraints*, not an architecture.  This module is the substrate
as a finite labelled transition system whose every transition is exact and whose
constraints are checked exhaustively at small evidence size.  It authorizes no
architecture, novelty, language, quantum or superiority claim.

Substrate ``Sigma = (E, Store, V, Ch, compose, revoke, revise, R)``:

* ``E = {0..n-1}``          finite evidence atoms (the things that can later be revoked);
* ``Store``                 named records, each ``(behaviour, profile, scope, epoch, channel)``
                            where ``profile`` is an antichain of inclusion-minimal
                            sufficient warrants over ``E`` (the RCL formal object of
                            ``revocation_complete_learning/rcl_model.py``, imported, not
                            re-implemented, so the checked object is the committed one);
* ``V``                     the checker: a record enters the store *live* only if ``V``
                            accepts its certificate against its behaviour (admission
                            gate; laundering = entering without ``V``);
* ``Ch``                    the five acquisition channels of the directive — instruction,
                            demonstration, interaction, experimentation, feedback — each
                            an admission path that produces a certificate of a stated
                            *kind*; the substrate does not fix a learning algorithm, it
                            fixes what warrant each kind can carry;
* ``compose``               skill composition with warrant preserved (Theorem S2);
* ``revoke``                evidence revocation ``R subset E`` (the RCL constraint, S3);
* ``revise``                self-revision: representation (coarsening of ``E``), learning
                            strategy (admission policy), architecture (store encoding);
                            each must preserve exact authority over what is already
                            known (S4, S5, S6);
* ``R``                     whole-system resource counters (#194 section 4), with the
                            conservation check S7.

Constraints checked exhaustively (every count carries its denominator):

  S1  admission soundness: every live record was admitted through ``V`` and ``V``
      accepted; a planted laundering path is caught;
  S2  composition: the composite's profile is the minimal antichain of unions
      ``J u K``; its liveness is the conjunction; its scope is the intersection;
      checked over all antichain pairs at n=3 (20 x 20) and all revocations, and
      over 4,000 sampled pairs at n=4 with a fixed seed;
  S3  revocation completeness: after ``revoke(R)`` the live set equals the set
      computed from the full profiles; a planted positive-only store (one witness
      per record, RCL-2b) is caught with the over-retraction witness;
  S4  representation revision: a coarsening ``pi`` of ``E`` under a *committed*
      policy (``over``: revoke every touched block; ``under``: revoke only covered
      blocks) answers every ``R`` in the admitted family ``Gamma`` exactly iff every
      ``R`` is a union of ``pi``-blocks -- each direction evaluated on every profile,
      with the ``abstain`` policy counted separately (an abstaining store is honest,
      not exact) and measurability judged by an independently written test; the
      coarsest such ``pi`` is the partition generated by ``Gamma``; a planted
      coarsening that splits some ``R`` produces a false-retain or false-retract
      witness (checked over all 15 partitions of 4 atoms x registered ``Gamma``).
      A first draft scored ``abstain`` inside the exactness loop, which made
      ``exact`` coincide with ``is_block_union`` by construction (VACUOUS_CONTRAST;
      found by Cursor Bugbot on PR #279 at e9a0222, repaired before merge);
  S5  strategy revision (admission-policy swap) leaves the liveness signature of
      every already-admitted record unchanged; a planted policy that re-admits a
      record under a weaker checker changes its status and is caught;
  S6  architecture revision (store re-encoding to the revocation signature and back)
      is authority-preserving because the signature determines the antichain
      (RCL-0); a planted encoding that drops one coordinate is caught;
  S7  resource conservation: every transition's counted-resource delta is
      non-negative and non-zero on the coordinate it charges (admission charges
      the checker, interaction charges queries, composition charges store bits,
      revocation charges revalidation work and records recourse); a planted
      "free" transition that mutates the store without charging is caught.

No-alarm controls compare two *independently written* liveness evaluators
(``rcl_model.live`` and ``rcl_model.live_via_active_set``) and two independently
written composition routines.  Mutation controls are asserted applied on a witness
*before* the check runs.  Exit contract of ``main``: ``0`` pass, ``1`` a check failed
for its registered reason, ``2`` ``CANNOT_CHECK`` (never a pass).

Parents (see theory/OCM_OPERATIONAL_SEMANTICS_V1.md): the profile is an ATMS label
(de Kleer 1986); admission is proof-carrying code (Necula 1997); S3 is
dependency-directed truth maintenance (Doyle 1979); S4 is Blackwell sufficiency /
lane-201 L1; S6 is RCL-0; S7 is the full-system honesty rule of #194 section 4.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import itertools
import json
import random
import time
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass, field, replace
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_RCL_MODEL = _HERE.parent / "revocation_complete_learning" / "rcl_model.py"


class CannotCheck(RuntimeError):
    """Raised when a check cannot be run; mapped to exit 2, never to a pass."""


def _load_rcl_model():
    spec = importlib.util.spec_from_file_location("rcl_model", _RCL_MODEL)
    if spec is None or spec.loader is None:
        raise CannotCheck(f"cannot load committed module {_RCL_MODEL}")
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception as exc:  # pragma: no cover - the CANNOT_CHECK route
        raise CannotCheck(f"rcl_model failed to import: {exc}") from exc
    return mod


rcl = _load_rcl_model()

Atom = int
Warrant = frozenset[Atom]
Profile = tuple[Warrant, ...]
Scope = frozenset[str]

CHANNELS: tuple[str, ...] = ("instruction", "demonstration", "interaction", "experimentation", "feedback")

# What warrant each channel's certificate kind can carry.  This is the substrate's
# only commitment about channels: it fixes *what is warranted*, not how it is learned.
#   positive  -> the certificate exhibits at least one full warrant (a checked proof / trace);
#   closure   -> the certificate additionally certifies that the listed warrants are all of them;
#   endpoint  -> the certificate only fixes behaviour; no warrant is exhibited (feedback);
#   query     -> interaction answers liveness queries; warrants are assembled from answers.
CHANNEL_CERTIFICATE_KIND: dict[str, str] = {
    "instruction": "positive",
    "demonstration": "positive",
    "interaction": "query",
    "experimentation": "closure",
    "feedback": "endpoint",
}


# ----------------------------------------------------------------------------
# Records, store, resources
# ----------------------------------------------------------------------------


@dataclass(frozen=True)
class Record:
    name: str
    behaviour: tuple[int, ...]
    profile: Profile  # canonical antichain over E
    scope: Scope
    epoch: int
    channel: str
    certificate_kind: str
    checked_by_V: bool
    complete: bool  # True iff the profile is certified complete (closure); False = positive-only


@dataclass
class Resources:
    """#194 section 4 vector, restricted to the coordinates this substrate has."""

    B_theta: int  # immutable substrate description (constant; the interpreter)
    B_mut: int = 0  # store bits
    V_cost: int = 0  # checker calls
    Q_queries: int = 0  # interaction queries
    W_update: int = 0  # records re-evaluated by a revocation (revalidation work)
    recourse: int = 0  # records whose status changed under revocation/revision
    abstentions: int = 0

    def as_tuple(self) -> tuple[int, ...]:
        return (self.B_theta, self.B_mut, self.V_cost, self.Q_queries, self.W_update, self.recourse, self.abstentions)


def store_bits(records: dict[str, Record], n: int) -> int:
    # one bit per atom per warrant plus one bit per record for the completeness flag
    return sum(len(r.profile) * n + 1 for r in records.values())


def store_digest(records: dict[str, Record]) -> str:
    payload = sorted((r.name, r.behaviour, tuple(sorted(tuple(sorted(w)) for w in r.profile)), tuple(sorted(r.scope)), r.epoch, r.complete) for r in records.values())
    return hashlib.sha256(repr(payload).encode()).hexdigest()


@dataclass
class Substrate:
    n: int
    records: dict[str, Record] = field(default_factory=dict)
    revoked: frozenset[Atom] = frozenset()
    epoch: int = 0
    resources: Resources = field(default_factory=lambda: Resources(B_theta=SUBSTRATE_DESCRIPTION_BITS))
    log: list[dict[str, object]] = field(default_factory=list)

    # ---- the checker V -----------------------------------------------------
    def V(self, behaviour: tuple[int, ...], certificate: dict[str, object]) -> bool:
        """Accept iff the certificate's exhibited warrants are well-formed over E and
        its claimed behaviour equals the behaviour being admitted.  Deliberately
        minimal: V checks the certificate, it does not solve the task (#194 C7)."""
        self.resources.V_cost += 1
        if certificate.get("behaviour") != behaviour:
            return False
        for w in certificate.get("warrants", ()):
            if not all(0 <= a < self.n for a in w):
                return False
        return True

    # ---- admission through a channel --------------------------------------
    def admit(self, name: str, behaviour: tuple[int, ...], certificate: dict[str, object], channel: str, scope: Scope, *, launder: bool = False) -> Record:
        if channel not in CHANNELS:
            raise CannotCheck(f"unknown channel {channel}")
        kind = CHANNEL_CERTIFICATE_KIND[channel]
        warrants = tuple(frozenset(w) for w in certificate.get("warrants", ()))
        if kind == "endpoint":
            warrants = ()  # feedback fixes behaviour only; no warrant is exhibited
        if kind == "query":
            self.resources.Q_queries += int(certificate.get("queries", 0))
        accepted = True if launder else self.V(behaviour, certificate)
        profile = rcl.canonical_profile(warrants) if warrants else ()
        rec = Record(
            name=name,
            behaviour=behaviour,
            profile=profile,
            scope=scope,
            epoch=self.epoch,
            channel=channel,
            certificate_kind=kind,
            checked_by_V=not launder,
            complete=(kind == "closure") and accepted,
        )
        if accepted:
            self.records[name] = rec
        self.resources.B_mut = store_bits(self.records, self.n)
        self.log.append({"op": "admit", "name": name, "channel": channel, "accepted": accepted, "laundered": launder})
        return rec

    # ---- liveness ------------------------------------------------------------
    def live(self, name: str, revoked: Iterable[Atom] | None = None) -> bool | None:
        """True/False, or None = abstain (positive-only record whose exhibited
        warrants are all dead: absence of a live witness is not proof of absence)."""
        rec = self.records[name]
        rv = self.revoked if revoked is None else frozenset(revoked)
        if not rec.profile:
            # certified-empty (closure) = dead; endpoint-only = no warrant to evaluate
            return False if rec.complete else None
        if rcl.live(rec.profile, rv):
            return True
        return False if rec.complete else None

    def live_set(self, revoked: Iterable[Atom] | None = None) -> dict[str, bool | None]:
        return {name: self.live(name, revoked) for name in self.records}

    # ---- composition ---------------------------------------------------------
    def compose(self, name: str, left: str, right: str) -> Record:
        p, q = self.records[left], self.records[right]
        profile = compose_profiles(p.profile, q.profile)
        rec = Record(
            name=name,
            behaviour=tuple(b for pair in zip(p.behaviour, q.behaviour, strict=True) for b in pair),
            profile=profile,
            scope=p.scope & q.scope,
            epoch=self.epoch,
            channel="composition",
            certificate_kind="bridge",
            checked_by_V=p.checked_by_V and q.checked_by_V,
            complete=p.complete and q.complete,
        )
        self.records[name] = rec
        self.resources.B_mut = store_bits(self.records, self.n)
        self.log.append({"op": "compose", "name": name, "left": left, "right": right})
        return rec

    # ---- revocation ----------------------------------------------------------
    def revoke(self, atoms: Iterable[Atom]) -> dict[str, bool | None]:
        before = self.live_set()
        self.revoked = self.revoked | frozenset(atoms)
        self.epoch += 1
        after = self.live_set()
        reopened = [k for k in after if after[k] != before[k]]
        self.resources.W_update += len(after)
        self.resources.recourse += len(reopened)
        self.resources.abstentions += sum(1 for v in after.values() if v is None)
        self.log.append({"op": "revoke", "atoms": sorted(atoms), "reopened": reopened})
        return after


SUBSTRATE_DESCRIPTION_BITS = 8 * len(Path(__file__).read_bytes()) if Path(__file__).exists() else 0


# ----------------------------------------------------------------------------
# Composition (two independent routines for the no-alarm control)
# ----------------------------------------------------------------------------


def compose_profiles(p: Profile, q: Profile) -> Profile:
    """Minimal antichain of {J u K : J in p, K in q}."""
    return rcl.canonical_profile(j | k for j in p for k in q)


def compose_profiles_b(p: Profile, q: Profile) -> Profile:
    """Independently written: enumerate unions, drop supersets by explicit scan."""
    unions = {frozenset(j) | frozenset(k) for j in p for k in q}
    minimal = [u for u in unions if not any(v < u for v in unions)]
    return tuple(sorted(minimal, key=lambda w: (len(w), sorted(w))))


# ----------------------------------------------------------------------------
# Representation revision: coarsening E by a partition
# ----------------------------------------------------------------------------

Partition = tuple[frozenset[Atom], ...]


def set_partitions(items: Sequence[Atom]) -> list[Partition]:
    if not items:
        return [()]
    first, rest = items[0], items[1:]
    out: list[Partition] = []
    for part in set_partitions(rest):
        out.append((frozenset({first}),) + part)
        for i, block in enumerate(part):
            out.append(part[:i] + (block | {first},) + part[i + 1 :])
    return [tuple(sorted(p, key=lambda b: sorted(b))) for p in out]


def is_block_union(r: frozenset[Atom], pi: Partition) -> bool:
    return all(block <= r or not (block & r) for block in pi)


def is_block_union_b(r: frozenset[Atom], pi: Partition) -> bool:
    """Independently written measurability test used by the S4 census, so that a
    mutation of ``is_block_union`` (which the coarse store consults) is detected
    against a judge it did not corrupt: a block is split iff it meets ``r`` in
    a proper nonempty subset."""
    for block in pi:
        k = len(block & r)
        if 0 < k < len(block):
            return False
    return True


def coarse_live(profile: Profile, r: frozenset[Atom], pi: Partition, policy: str) -> bool | None:
    """Liveness a coarse store can compute.  If ``r`` is a block union the answer is
    exact.  Otherwise the store must choose: ``over`` revokes every touched block
    (may falsely retract), ``under`` revokes only fully covered blocks (may falsely
    retain), ``abstain`` returns None."""
    if is_block_union(r, pi):
        return rcl.live(profile, r)
    if policy == "abstain":
        return None
    if policy == "over":
        rr = frozenset(a for block in pi if block & r for a in block)
    elif policy == "under":
        rr = frozenset(a for block in pi if block <= r for a in block)
    else:
        raise CannotCheck(f"unknown coarse policy {policy}")
    return rcl.live(profile, rr)


def partition_generated_by(gamma: Sequence[frozenset[Atom]], n: int) -> Partition:
    """Coarsest partition of E for which every R in gamma is a block union: atoms
    are in the same block iff no R separates them."""
    blocks: dict[tuple[bool, ...], set[Atom]] = {}
    for a in range(n):
        key = tuple(a in r for r in gamma)
        blocks.setdefault(key, set()).add(a)
    return tuple(sorted((frozenset(b) for b in blocks.values()), key=lambda b: sorted(b)))


def is_coarser_or_equal(pi: Partition, rho: Partition) -> bool:
    """pi is coarser than or equal to rho: every rho-block lies inside a pi-block."""
    return all(any(rb <= pb for pb in pi) for rb in rho)


# ----------------------------------------------------------------------------
# Architecture revision: store encodings
# ----------------------------------------------------------------------------


def encode_signature(profile: Profile, n: int) -> tuple[bool, ...]:
    return rcl.signature(profile, n)


def decode_signature(sig: tuple[bool, ...], n: int, table: dict[tuple[bool, ...], Profile]) -> Profile:
    return table[sig]


def encode_dropping_last(profile: Profile, n: int) -> tuple[bool, ...]:
    return rcl.signature(profile, n)[:-1]


# ----------------------------------------------------------------------------
# Checks
# ----------------------------------------------------------------------------


def _fresh(n: int) -> Substrate:
    return Substrate(n=n)


def check_S1_admission(n: int = 4) -> dict[str, object]:
    s = _fresh(n)
    beh = (0, 1, 2, 3)
    cert_ok = {"behaviour": beh, "warrants": [[0, 1], [2]]}
    cert_bad = {"behaviour": (9, 9, 9, 9), "warrants": [[0]]}
    s.admit("good", beh, cert_ok, "instruction", frozenset({"c1"}))
    s.admit("bad", beh, cert_bad, "instruction", frozenset({"c1"}))
    s.admit("laundered", beh, cert_bad, "instruction", frozenset({"c1"}), launder=True)
    invariant_violations = [r.name for r in s.records.values() if not r.checked_by_V]
    return {
        "admitted": sorted(s.records),
        "rejected_by_V": "bad" not in s.records,
        "laundering_planted": "laundered" in s.records,
        "laundering_caught_by_invariant": invariant_violations == ["laundered"],
        "V_calls": s.resources.V_cost,
        "holds": ("good" in s.records) and ("bad" not in s.records) and invariant_violations == ["laundered"],
    }


def check_S2_composition(n_exhaustive: int = 3, n_sampled: int = 4, samples: int = 4000, seed: int = 20260904) -> dict[str, object]:
    out: dict[str, object] = {}
    # exhaustive at n=3
    profiles = rcl.enumerate_antichains(n_exhaustive)
    revs = [frozenset(r) for k in range(n_exhaustive + 1) for r in itertools.combinations(range(n_exhaustive), k)]
    pairs = 0
    checks = 0
    bad: list[dict[str, object]] = []
    for p in profiles:
        for q in profiles:
            pairs += 1
            c = compose_profiles(p, q)
            if c != compose_profiles_b(p, q):
                bad.append({"p": p, "q": q, "reason": "two composition routines disagree"})
            for r in revs:
                checks += 1
                if rcl.live(c, r) != (rcl.live(p, r) and rcl.live(q, r)):
                    bad.append({"p": p, "q": q, "r": sorted(r), "reason": "liveness not conjunctive"})
    out["exhaustive"] = {"n": n_exhaustive, "antichains": len(profiles), "pairs": pairs, "liveness_checks": checks, "violations": bad[:3], "holds": not bad}
    # sampled at n=4
    rng = random.Random(seed)
    profiles4 = rcl.enumerate_antichains(n_sampled)
    revs4 = [frozenset(r) for k in range(n_sampled + 1) for r in itertools.combinations(range(n_sampled), k)]
    bad4: list[dict[str, object]] = []
    for _ in range(samples):
        p, q = rng.choice(profiles4), rng.choice(profiles4)
        c = compose_profiles(p, q)
        if c != compose_profiles_b(p, q):
            bad4.append({"reason": "routines disagree"})
        for r in revs4:
            if rcl.live(c, r) != (rcl.live(p, r) and rcl.live(q, r)):
                bad4.append({"reason": "liveness not conjunctive"})
    out["sampled"] = {"n": n_sampled, "antichains": len(profiles4), "pairs": samples, "seed": seed, "liveness_checks": samples * len(revs4), "violations": bad4[:3], "holds": not bad4}
    # scope intersection with a countermodel for union scope
    s = _fresh(n_sampled)
    s.admit("p", (0, 1, 2, 3), {"behaviour": (0, 1, 2, 3), "warrants": [[0]]}, "instruction", frozenset({"a", "b"}))
    s.admit("q", (0, 1, 2, 3), {"behaviour": (0, 1, 2, 3), "warrants": [[1]]}, "demonstration", frozenset({"b", "c"}))
    comp = s.compose("pq", "p", "q")
    union_scope = s.records["p"].scope | s.records["q"].scope
    countermodels = sorted(union_scope - comp.scope)
    out["scope"] = {"composite_scope": sorted(comp.scope), "union_scope_countermodels": countermodels, "holds": comp.scope == frozenset({"b"}) and countermodels == ["a", "c"]}
    out["holds"] = bool(out["exhaustive"]["holds"] and out["sampled"]["holds"] and out["scope"]["holds"])
    return out


def check_S3_revocation_completeness(n: int = 4) -> dict[str, object]:
    profiles = rcl.enumerate_antichains(n)
    revs = [frozenset(r) for k in range(n + 1) for r in itertools.combinations(range(n), k)]
    # complete store: every profile admitted through experimentation (closure certificate)
    s = _fresh(n)
    for i, p in enumerate(profiles):
        s.admit(f"r{i}", (i % 8,), {"behaviour": (i % 8,), "warrants": [sorted(w) for w in p]}, "experimentation", frozenset({"c"}))
    checks = 0
    mismatches = 0
    agreement_two_evaluators = 0
    for r in revs:
        got = s.live_set(r)
        for i, p in enumerate(profiles):
            checks += 1
            expect = rcl.live(p, r)
            if got[f"r{i}"] != expect:
                mismatches += 1
            if rcl.live(p, r) == rcl.live_via_active_set(p, r, n):
                agreement_two_evaluators += 1
    # planted positive-only store: keeps one witness (first warrant) per record, RCL-2b
    s1 = _fresh(n)
    over_retractions = 0
    abstentions = 0
    witness = None
    for i, p in enumerate(profiles):
        if not p:
            continue
        one = [sorted(p[0])]
        s1.admit(f"r{i}", (i % 8,), {"behaviour": (i % 8,), "warrants": one}, "instruction", frozenset({"c"}))
    for r in revs:
        got = s1.live_set(r)
        for i, p in enumerate(profiles):
            if not p:
                continue
            truth = rcl.live(p, r)
            g = got[f"r{i}"]
            if truth and g is None:
                abstentions += 1
                if witness is None:
                    witness = {"profile": [sorted(w) for w in p], "revoked": sorted(r), "emitted_witness": sorted(p[0])}
            if truth and g is False:
                over_retractions += 1
    return {
        "n": n,
        "antichains": len(profiles),
        "revocations": len(revs),
        "liveness_checks": checks,
        "mismatches": mismatches,
        "two_evaluator_agreement": {"agree": agreement_two_evaluators, "denominator": checks},
        "planted_positive_only_store": {
            "false_retractions": over_retractions,
            "abstentions_where_truth_is_live": abstentions,
            "first_witness": witness,
            "caught": abstentions > 0 and over_retractions == 0,
            "reading": "a positive-only record whose emitted witness dies must abstain, never retract (RCL-2b); the substrate abstains",
        },
        "holds": mismatches == 0 and agreement_two_evaluators == checks and abstentions > 0 and over_retractions == 0,
    }


def check_S4_representation_revision(n: int = 4) -> dict[str, object]:
    profiles = rcl.enumerate_antichains(n)
    partitions = set_partitions(list(range(n)))
    gammas = {
        "singletons": [frozenset({a}) for a in range(n)],
        "pairs_01_23": [frozenset({0, 1}), frozenset({2, 3})],
        "nested_0_01_012": [frozenset({0}), frozenset({0, 1}), frozenset({0, 1, 2})],
        "one_set_12": [frozenset({1, 2})],
    }
    rows: list[dict[str, object]] = []
    all_ok = True
    for gname, gamma in gammas.items():
        generated = partition_generated_by(gamma, n)
        exact_partitions: list[Partition] = []
        for pi in partitions:
            # measurability judged by the independently written test, never by the
            # function the coarse store itself consults
            measurable = all(is_block_union_b(r, pi) for r in gamma)
            # exactness of each *committed* policy, evaluated on every profile and
            # every admitted revocation; abstention is counted separately because an
            # abstaining store is honest, not exact
            exact_over = all(coarse_live(p, r, pi, "over") == rcl.live(p, r) for p in profiles for r in gamma)
            exact_under = all(coarse_live(p, r, pi, "under") == rcl.live(p, r) for p in profiles for r in gamma)
            abstains = sum(1 for p in profiles for r in gamma if coarse_live(p, r, pi, "abstain") is None)
            if exact_over != measurable or exact_under != measurable:
                all_ok = False
            if (abstains == 0) != measurable:
                all_ok = False
            if exact_over and exact_under:
                exact_partitions.append(pi)
        coarsest_is_generated = generated in exact_partitions and all(is_coarser_or_equal(generated, pi) for pi in exact_partitions)
        if not coarsest_is_generated:
            all_ok = False
        rows.append({
            "gamma": gname,
            "partitions_examined": len(partitions),
            "exact_partitions": len(exact_partitions),
            "generated_partition": [sorted(b) for b in generated],
            "generated_is_coarsest_exact": coarsest_is_generated,
            "policies_evaluated": ["over", "under"],
            "abstain_counted_separately": True,
        })
    # planted: merge atoms 1 and 2 while gamma separates them (R = {1}); must produce a witness
    pi_bad: Partition = (frozenset({0}), frozenset({1, 2}), frozenset({3}))
    r = frozenset({1})
    false_retract = None
    false_retain = None
    for p in profiles:
        truth = rcl.live(p, r)
        if truth and coarse_live(p, r, pi_bad, "over") is False and false_retract is None:
            false_retract = {"profile": [sorted(w) for w in p], "revoked": [1]}
        if (not truth) and coarse_live(p, r, pi_bad, "under") is True and false_retain is None:
            false_retain = {"profile": [sorted(w) for w in p], "revoked": [1]}
    planted_caught = false_retract is not None and false_retain is not None
    if not planted_caught:
        all_ok = False
    return {
        "n": n,
        "antichains": len(profiles),
        "partitions": len(partitions),
        "families": rows,
        "planted_split_coarsening": {"partition": [sorted(b) for b in pi_bad], "false_retract_witness": false_retract, "false_retain_witness": false_retain, "caught": planted_caught},
        "holds": all_ok,
    }


def check_S5_strategy_revision(n: int = 4) -> dict[str, object]:
    profiles = rcl.enumerate_antichains(n)
    revs = [frozenset(r) for k in range(n + 1) for r in itertools.combinations(range(n), k)]
    s = _fresh(n)
    for i, p in enumerate(profiles):
        if p:
            s.admit(f"r{i}", (i % 8,), {"behaviour": (i % 8,), "warrants": [sorted(w) for w in p]}, "experimentation", frozenset({"c"}))
    before = {name: tuple(s.live(name, r) for r in revs) for name in s.records}
    # strategy swap: from now on admit through demonstration; already-admitted records untouched
    s.admit("new", (7,), {"behaviour": (7,), "warrants": [[0]]}, "demonstration", frozenset({"c"}))
    after = {name: tuple(s.live(name, r) for r in revs) for name in before}
    unchanged = sum(1 for k in before if before[k] == after[k])
    # planted: a policy that re-admits an existing record through feedback (endpoint) — loses its warrant
    s_bad = _fresh(n)
    s_bad.admit("r", (1,), {"behaviour": (1,), "warrants": [[0], [1]]}, "experimentation", frozenset({"c"}))
    sig_before = tuple(s_bad.live("r", r) for r in revs)
    s_bad.admit("r", (1,), {"behaviour": (1,)}, "feedback", frozenset({"c"}))
    sig_after = tuple(s_bad.live("r", r) for r in revs)
    return {
        "records": len(before),
        "revocations": len(revs),
        "signatures_unchanged": unchanged,
        "planted_readmission_under_weaker_channel": {"before": sig_before, "after": sig_after, "caught": sig_before != sig_after},
        "holds": unchanged == len(before) and sig_before != sig_after,
    }


def check_S6_architecture_revision(n: int = 4) -> dict[str, object]:
    profiles = rcl.enumerate_antichains(n)
    table = {rcl.signature(p, n): p for p in profiles}
    injective = len(table) == len(profiles)
    roundtrip = sum(1 for p in profiles if decode_signature(encode_signature(p, n), n, table) == p)
    dropped = {}
    collisions = 0
    for p in profiles:
        k = encode_dropping_last(p, n)
        if k in dropped:
            collisions += 1
        dropped[k] = p
    return {
        "n": n,
        "antichains": len(profiles),
        "signature_injective": injective,
        "roundtrip_exact": roundtrip,
        "planted_encoding_dropping_last_coordinate": {"distinct_codes": len(dropped), "collisions": collisions, "caught": collisions > 0},
        "holds": injective and roundtrip == len(profiles) and collisions > 0,
    }


def check_S7_resource_conservation(n: int = 4) -> dict[str, object]:
    s = _fresh(n)
    deltas: list[dict[str, object]] = []

    def step(label: str, fn: Callable[[], object], charged: str) -> None:
        before = s.resources.as_tuple()
        dig_before = store_digest(s.records)
        fn()
        after = s.resources.as_tuple()
        dig_after = store_digest(s.records)
        names = ("B_theta", "B_mut", "V_cost", "Q_queries", "W_update", "recourse", "abstentions")
        d = {k: a - b for k, a, b in zip(names, after, before, strict=True)}
        deltas.append({"op": label, "delta": d, "store_changed": dig_before != dig_after, "charged": charged, "charged_positive": d[charged] > 0, "B_theta_constant": d["B_theta"] == 0})

    step("admit/instruction", lambda: s.admit("a", (1,), {"behaviour": (1,), "warrants": [[0], [1, 2]]}, "instruction", frozenset({"c"})), "V_cost")
    step("admit/interaction", lambda: s.admit("b", (2,), {"behaviour": (2,), "warrants": [[3]], "queries": 4}, "interaction", frozenset({"c"})), "Q_queries")
    step("compose", lambda: s.compose("ab", "a", "b"), "B_mut")
    step("revoke{3}", lambda: s.revoke({3}), "W_update")
    honest_ok = all(d["charged_positive"] and d["B_theta_constant"] for d in deltas)
    revoke_delta = deltas[-1]["delta"]
    honest_ok = honest_ok and revoke_delta["recourse"] == 2 and revoke_delta["W_update"] == 3  # b and ab reopen; three records re-evaluated
    # planted: a "free" transition that mutates the store without charging any counter
    dig_before = store_digest(s.records)
    before = s.resources.as_tuple()
    s.records["a"] = replace(s.records["a"], profile=())
    free = {"store_changed": store_digest(s.records) != dig_before, "any_counter_changed": s.resources.as_tuple() != before}
    free["caught"] = free["store_changed"] and not free["any_counter_changed"]
    return {"transitions": deltas, "planted_free_mutation": free, "holds": honest_ok and free["caught"]}


# ----------------------------------------------------------------------------
# Mutation controls (asserted applied before the check)
# ----------------------------------------------------------------------------


def mutation_controls(n: int = 4) -> dict[str, object]:
    out: dict[str, object] = {}
    # M1: composition that takes intersections instead of unions -> S2 liveness conjunction fails
    orig = compose_profiles
    witness_p, witness_q = (frozenset({0}),), (frozenset({1}),)

    def bad_compose(p: Profile, q: Profile) -> Profile:
        return rcl.canonical_profile(j & k for j in p for k in q)

    applied = bad_compose(witness_p, witness_q) != orig(witness_p, witness_q)
    globals()["compose_profiles"] = bad_compose
    try:
        res = check_S2_composition(samples=200)
    finally:
        globals()["compose_profiles"] = orig
    out["M1_compose_by_intersection"] = {"applied": applied, "detected": not res["holds"], "registered_reason": "S2 liveness must stop being conjunctive"}

    # M2: liveness that ignores revocation -> S3 mismatches, and the two evaluators disagree
    orig_live = rcl.live
    applied2 = orig_live((frozenset({0}),), frozenset({0})) is False

    def bad_live(profile: Profile, revoked: Iterable[Atom]) -> bool:
        return bool(profile)

    applied2 = applied2 and bad_live((frozenset({0}),), frozenset({0})) is True
    rcl.live = bad_live
    try:
        res3 = check_S3_revocation_completeness(n)
    finally:
        rcl.live = orig_live
    out["M2_live_ignores_revocation"] = {"applied": applied2, "detected": not res3["holds"], "two_evaluator_agreement": res3["two_evaluator_agreement"], "registered_reason": "the two evaluators must disagree and the completeness invariant must fail"}

    # M3: block-union test that always says True -> S4 exactness != measurability
    orig_bu = is_block_union
    applied3 = orig_bu(frozenset({1}), (frozenset({0}), frozenset({1, 2}), frozenset({3}))) is False
    globals()["is_block_union"] = lambda r, pi: True
    try:
        res4 = check_S4_representation_revision(n)
    finally:
        globals()["is_block_union"] = orig_bu
    # registered reason: with the store's block-union test corrupted, the committed
    # policies report exact answers on split partitions, so exactness disagrees with
    # the independent measurability judge on at least one (partition, family)
    m3_reason_fires = any(
        r["exact_partitions"] != {"singletons": 1, "pairs_01_23": 4, "nested_0_01_012": 1, "one_set_12": 4}[r["gamma"]]
        for r in res4["families"]
    )
    out["M3_block_union_always_true"] = {"applied": applied3, "detected": (not res4["holds"]) and m3_reason_fires, "exact_partition_counts_under_mutation": {r["gamma"]: r["exact_partitions"] for r in res4["families"]}, "registered_reason": "S4 exactness must disagree with the independent measurability judge (exact-partition counts change)"}

    # M4: resource counter that never charges V -> S7 charged_positive fails
    orig_V = Substrate.V

    def free_V(self, behaviour, certificate):  # type: ignore[no-untyped-def]
        return orig_V(self, behaviour, certificate) if False else certificate.get("behaviour") == behaviour

    probe = _fresh(n)
    free_V(probe, (1,), {"behaviour": (1,)})
    applied4 = probe.resources.V_cost == 0
    Substrate.V = free_V  # type: ignore[method-assign]
    try:
        res7 = check_S7_resource_conservation(n)
    finally:
        Substrate.V = orig_V  # type: ignore[method-assign]
    out["M4_checker_not_charged"] = {"applied": applied4, "detected": not res7["holds"], "registered_reason": "admission must charge V_cost"}
    out["planted"] = 4
    out["detected"] = sum(1 for k, v in out.items() if isinstance(v, dict) and v.get("detected"))
    return out


# ----------------------------------------------------------------------------
# Driver
# ----------------------------------------------------------------------------


def run_reference_semantics(n: int = 4) -> dict[str, object]:
    t0 = time.perf_counter()
    if n > rcl.MAX_EXHAUSTIVE_N:
        raise CannotCheck(f"exhaustive antichain enumeration capped at n={rcl.MAX_EXHAUSTIVE_N}")
    checks = {
        "S1_admission": check_S1_admission(n),
        "S2_composition": check_S2_composition(),
        "S3_revocation_completeness": check_S3_revocation_completeness(n),
        "S4_representation_revision": check_S4_representation_revision(n),
        "S5_strategy_revision": check_S5_strategy_revision(n),
        "S6_architecture_revision": check_S6_architecture_revision(n),
        "S7_resource_conservation": check_S7_resource_conservation(n),
    }
    failed = [k for k, v in checks.items() if not v["holds"]]
    if failed:
        raise AssertionError(f"constraints failed: {failed}")
    muts = mutation_controls(n)
    if muts["detected"] != muts["planted"]:
        raise AssertionError(f"mutation controls: {muts['detected']}/{muts['planted']} detected")
    return {
        "schema": "orion.ocm.reference-semantics.exact-results.v1",
        "terminal": "PASS_SUBSTRATE_CONSTRAINTS_EXACT",
        "substrate": {
            "evidence_atoms": n,
            "channels": list(CHANNELS),
            "channel_certificate_kind": CHANNEL_CERTIFICATE_KIND,
            "profile_model": "revocation_complete_learning/rcl_model.py (imported, not re-implemented)",
            "B_theta_bits": SUBSTRATE_DESCRIPTION_BITS,
        },
        "checks": checks,
        "controls": {"mutations": muts, "M0_unmutated": {"applied": True, "all_checks_pass": True}},
        "runtime_seconds": round(time.perf_counter() - t0, 3),
        "authority": {
            "finite_model_only": True,
            "semantics_frozen": False,
            "proof_assistant_encoding": "CANNOT_CHECK: no toolchain provisioned",
            "novelty_established": False,
            "architecture_superiority_established": False,
        },
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    try:
        result = run_reference_semantics()
    except CannotCheck as exc:
        print(json.dumps({"terminal": "CANNOT_CHECK", "reason": str(exc)}, indent=2))
        return 2
    except AssertionError as exc:
        print(json.dumps({"terminal": "FAIL", "error": str(exc)}, indent=2))
        return 1
    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True, default=str))
    else:
        c = result["checks"]
        print(
            f"PASS substrate constraints S1-S7 at n=4: S2 {c['S2_composition']['exhaustive']['liveness_checks']} exhaustive + "
            f"{c['S2_composition']['sampled']['liveness_checks']} sampled liveness checks; S3 {c['S3_revocation_completeness']['liveness_checks']} checks, "
            f"{c['S3_revocation_completeness']['mismatches']} mismatches; S4 {c['S4_representation_revision']['partitions']} partitions x "
            f"{len(c['S4_representation_revision']['families'])} families; S6 {c['S6_architecture_revision']['antichains']} antichains round-trip; "
            f"{result['controls']['mutations']['detected']}/{result['controls']['mutations']['planted']} mutations detected; {result['runtime_seconds']} s"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
